name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**"
      - ".git*"
      - ".ped*"
      - "*.md"
      - "LICENSE"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**"
      - ".git*"
      - ".ped*"
      - "*.md"
      - "LICENSE"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install gcc-multilib
        if: matrix.target == 'i686-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib

      - name: Install Rust for ${{ matrix.target }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Build ${{ matrix.target }}
        run: |
          cargo build --target ${{ matrix.target }}
          cargo test --target ${{ matrix.target }} --no-fail-fast
