name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Trigger Publish for Homebrew
        run: |
          TAG=$(gh release view --json tagName --jq ".tagName")
          echo "TAG=${TAG}"

          curl -v -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ env.GH_TOKEN }}" \
            https://api.github.com/repos/davidledwards/homebrew-ped/dispatches \
            -d '{"event_type": "release", "client_payload": { "tag": "${TAG}" }}'
