name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GH_TOKEN: ${{ secrets.PAT }}

    steps:
      - uses: actions/checkout@v4
      # - name: Trigger publish for Homebrew
      #   run: |
      #     TAG=$(gh release view --json tagName --jq ".tagName")

      #     gh api --method POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       /repos/davidledwards/homebrew-ped/dispatches \
      #       -f "event_type=publish" \
      #       -F "client_payload[tag]=${TAG}"

      - name: Checkout Homebrew tap repository
        uses: actions/checkout@v4
        with:
          repository: davidledwards/homebrew-ped
          path: homebrew-ped
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}

      - name: Download release artifacts
        run: |
          mkdir artifacts
          gh release download ${{ github.ref_name }} \
            --repo ${{ github.repository }} \
            --dir artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Homebrew formula
        run: |
          VERSION=${GITHUB_REF_NAME}
          FORMULA=homebrew-ped/Formula/ped.rb

          # sed -i "s/version \".*\"/version \"${VERSION}\"/" $FORMULA
          sed "s/version \".*\"/version \"${VERSION}\"/" $FORMULA

          TARGETS=(\
            "aarch64-apple-darwin",\
            "x86_64-apple-darwin",\
            "x86_64-unknown-linux-gnu",\
            "i686-unknown-linux-gnu"\
          )

          for TARGET in "${TARGETS[@]}"
          do
            SHA=$(cut -d ' ' -f1 artifacts/ped-v${VERSION}-${TARGET}.tar.gz.sha256)
            # sed -i "s/sha256 \".*\" # ${TARGET}/sha256 \"${SHA}\" # $(TARGET}/" $FORMULA
            sed "s/sha256 \".*\" # ${TARGET}/sha256 \"${SHA}\" # $(TARGET}/" $FORMULA
          done

      # - name: Commit and push changes
      #   run: |
      #     cd homebrew-ped
      #     git config user.name "github-actions[bot]"
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git add Formula/ped.rb
      #     git commit -m "Update ped formula to version ${GITHUB_REF_NAME}"
      #     git push
