name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4
      - name: Trigger Publish for Homebrew
        run: |
          TAG=$(gh release view --json tagName --jq ".tagName")

          gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/davidledwards/homebrew-ped/dispatches \
            -f "event_type=publish" \
            -F "client_payload[tag]=${TAG}"
