name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin

          - os: macos-latest
            target: x86_64-apple-darwin

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Set Version
        run: |
          VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r ".packages[0].version")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and Test
        run: |
          echo "building version ${{ env.VERSION }} for {{ matrix.target }}"
          cargo build --release
          cargo test --release --no-fail-fast
          # tar -czf ${TAR_FILE} ${TARGET_DIR}/ped
          # shasum -a 256 ${TAR_FILE} > ${TAR_FILE}.sha256
