name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: macos-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: aarch64-apple-darwin

      - name: Create Release
        run: |
          VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r ".packages[0].version")
          gh release create v${VERSION} --title ${VERSION} --generate-notes

  build-and-upload:
    needs: create-release

    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Set Variables
        run: |
          VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r ".packages[0].version")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          TAG=v${VERSION}
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }}
          cargo test --release --target ${{ matrix.target }} --no-fail-fast

      - name: Upload Artifacts
        run: |
          BIN_DIR=target/${{ matrix.target }}/release
          TAR_FILE=${BIN_DIR}/ped-${{ env.VERSION }}-${{ matrix.target }}.tar.gz
          SHA_FILE=${TAR_FILE}.sha256

          tar -czf ${TAR_FILE} ${BIN_DIR}/ped
          shasum -a 256 ${TAR_FILE} > ${SHA_FILE}

          gh release upload --clobber ${{ env.TAG }} ${TAR_FILE} ${SHA_FILE}
